### PR TITLE
Fixes #8  - where Dead Memcached Servers Cause The Entire Cluster To Be…

### LINKED ISSUE #8: Dead memcache servers cause the entire cluster to be inaccessible
When a single node fails because of network connectivity or any other node issue, the library marks the entire cluster to be inaccessible and all further requests are blocked till deadtimeout or cluster polling (configured) passes.

### PR DESCRIPTION
**Pull request by pdelossantos**
… Inaccessible

### CODE REVIEW

File: Amazon.ElastiCacheCluster/Pools/AutoServerPool.cs [hunk 1]
```diff
@@ -299,13 +299,35 @@ void IDisposable.Dispose()
...
+                    continue;
+                }
+
+                aliveList.Add(node);
+            }
+
+            newLocator.Initialize(aliveList);
+
+            // Retain All Nodes List With IsAlive Status
+            aliveList.AddRange(deadList);
```
Comment (normj) [inline Amazon.ElastiCacheCluster/Pools/AutoServerPool.cs]: Shouldn't aliveLIst and deadList be combined into a separate collection. I assume NodeLocator is creating a separate list today when the aliveList is passed into Initialize which is why it is working now but I worry that might change sometime in the future and cause a painful to diagnose bug.

**Comment by pdelossantos** [comment]
@normj i have updated the code to add a new variable for easier debugging in the future if another issue comes
